version: 0.2
language: en
words:
  - apdisk
  - donotpresent
  - ehthumbs
  - encryptable
  - folderid
  - fseventsd
  - gobwas
  - icns
  - knownfolderid
  - mapi
  - samber
  - stackdump
  - timemachine
